# Site settings
title: Engineering Ascend
description: Comprehensive system design learning resource for technical interview preparation and scalable system architecture
url: https://vikneshrajsp.github.io
baseurl: /software-engineering-guide

# Theme settings
remote_theme: pages-themes/architect

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  building-blocks:
    output: true
  challenges:
    output: true

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore
