# GitHub Pages Configuration
# This file configures how GitHub Pages renders the markdown files

# Site settings
title: System Design Guide
description: Comprehensive learning resource for system design interviews
url: "https://vikneshrajsp.github.io/InterviewPrep"
baseurl: "/InterviewPrep"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  building-blocks:
    output: true
    permalink: /building-blocks/:name/
  challenges:
    output: true
    permalink: /system-design-challenges/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "building-blocks"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "challenges"
    values:
      layout: "default"

# Exclude from processing
exclude:
  - node_modules
  - .git
  - .github
  - scripts
  - assets
  - package.json
  - package-lock.json
  - .gitignore
