# Site settings
title: Engineering Ascend
description: Comprehensive system design learning resource for technical interview preparation and scalable system architecture
url: https://vikneshrajsp.github.io
baseurl: /software-engineering-guide

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore
